### ISSUE TITLE
6.6.7和6.5.1.3两个版本在Ubuntu上会报segmentation fault错误。

### ISSUE THREAD

**Issue by DennisXie** [vnpy/vnpy_tts#17]
具体问题我提在vnpy那边了，[issue3383](https://github.com/vnpy/vnpy/issues/3383)
目前发现6.5.1.2的so库和vnpy_ctp==6.5.1.2的so库是一样的，没有使用openctp提供的so库。
6.6.7版本的so库和openctp提供的so库不一样，但不知道是不是openctp那边升级导致的。但是不管使用哪个so库都会出现segmentation fault错误。

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_tts/pull/18
