### ISSUE TITLE
vnpy_tts 6.6.7.3无法连上simnow的CTP接口

### ISSUE THREAD

**Issue by sparkkk** [vnpy/vnpy_tts#22]
操作系统ubuntu18.04
vnpy版本3.7.0
python版本3.8
2023年8月31日测试，使用openctp同时连接simnow的交易和行情前置。
启动vnpy命令行后不停地打log"连接成功"和"连接断开，原因0"。
交易前置连接openctp自身的账号，行情连接simnow也是如此。
动态库没有替换过。

**Comment by vnpy** [comment]
TTS和CTP的dll重名，因此不能同时加载，会发生冲突

**Comment by sparkkk** [comment]
> TTS和CTP的dll重名，因此不能同时加载，会发生冲突

这个我注意了，没有同时import两个python包

**Comment by vnpy** [comment]
那么TTS接口，不能用于连接CTP的柜台环境了（比如SimNow），两者DLL是不兼容的
