### ISSUE TITLE
请问有没有办法支持Python 3.6 32 位

### ISSUE THREAD

**Issue by Jojoliu66** [vnpy/vnpy_tts#24]
请问有没有办法支持Python 3.6 32 位，我在安装完tts==6.5.10之后，他会报以下错误：
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from vnpy_tts import TtsGateway
ImportError: cannot import name 'TtsGateway'

**Comment by vnpy** [comment]
可以尝试下载源代码后自行编译，理论上可以实现

**Comment by Jojoliu66** [comment]
请问vnttsmd.cpp提示我缺少stdafx.h文件要怎么解决
