### ISSUE TITLE
python3.11.4 安装出错

### ISSUE THREAD

**Issue by Lsgo** [vnpy/vnpy_tts#25]
Looking in indexes: https://pypi.doubanio.com/simple
Collecting vnpy_tts
  Using cached https://mirrors.cloud.tencent.com/pypi/packages/d3/b8/34b3538b7edd1e1670461652205c342bd6a1ec6e17151aef89bde0c18250/vnpy_tts-6.7.2.0.tar.gz (2.1 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: importlib_metadata in d:\miniconda3\lib\site-packages (from vnpy_tts) (7.0.1)
Requirement already satisfied: zipp>=0.5 in d:\miniconda3\lib\site-packages (from importlib_metadata->vnpy_tts) (3.17.0)
Building wheels for collected packages: vnpy_tts
  Building wheel for vnpy_tts (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [457 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\vnpy_tts
      copying vnpy_tts\__init__.py -> build\lib.win-amd64-cpython-311\vnpy_tts
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api
      copying vnpy_tts\api\tts_constant.py -> build\lib.win-amd64-cpython-311\vnpy_tts\api
      copying vnpy_tts\api\__init__.py -> build\lib.win-amd64-cpython-311\vnpy_tts\api
      creating build\lib.win-amd64-cpython-311\vnpy_tts\gateway
      copying vnpy_tts\gateway\tts_gateway.py -> build\lib.win-amd64-cpython-311\vnpy_tts\gateway
      copying vnpy_tts\gateway\__init__.py -> build\lib.win-amd64-cpython-311\vnpy_tts\gateway
      running egg_info
      writing vnpy_tts.egg-info\PKG-INFO
      writing dependency_links to vnpy_tts.egg-info\dependency_links.txt
      writing requirements to vnpy_tts.egg-info\requires.txt
      writing top-level names to vnpy_tts.egg-info\top_level.txt
      reading manifest file 'vnpy_tts.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.pyd' under directory 'vnpy_tts'
      adding license file 'LICENSE'
      writing manifest file 'vnpy_tts.egg-info\SOURCES.txt'
      D:\miniconda3\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'vnpy_tts.api.vntts.vnttsmd' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'vnpy_tts.api.vntts.vnttsmd' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'vnpy_tts.api.vntts.vnttsmd' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'vnpy_tts.api.vntts.vnttsmd' to be distributed and are
              already explicitly excluding 'vnpy_tts.api.vntts.vnttsmd' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      D:\miniconda3\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'vnpy_tts.api.vntts.vnttstd' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'vnpy_tts.api.vntts.vnttstd' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'vnpy_tts.api.vntts.vnttstd' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'vnpy_tts.api.vntts.vnttstd' to be distributed and are
              already explicitly excluding 'vnpy_tts.api.vntts.vnttstd' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      D:\miniconda3\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'vnpy_tts.api.generator' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'vnpy_tts.api.generator' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'vnpy_tts.api.generator' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'vnpy_tts.api.generator' to be distributed and are
              already explicitly excluding 'vnpy_tts.api.generator' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      D:\miniconda3\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'vnpy_tts.api.include.pybind11' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'vnpy_tts.api.include.pybind11' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'vnpy_tts.api.include.pybind11' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'vnpy_tts.api.include.pybind11' to be distributed and are
              already explicitly excluding 'vnpy_tts.api.include.pybind11' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      D:\miniconda3\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'vnpy_tts.api.include.pybind11.detail' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'vnpy_tts.api.include.pybind11.detail' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'vnpy_tts.api.include.pybind11.detail' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'vnpy_tts.api.include.pybind11.detail' to be distributed and are
              already explicitly excluding 'vnpy_tts.api.include.pybind11.detail' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      D:\miniconda3\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'vnpy_tts.api.include.tts' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'vnpy_tts.api.include.tts' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'vnpy_tts.api.include.tts' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'vnpy_tts.api.include.tts' to be distributed and are
              already explicitly excluding 'vnpy_tts.api.include.tts' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      D:\miniconda3\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'vnpy_tts.api.libs' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'vnpy_tts.api.libs' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'vnpy_tts.api.libs' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'vnpy_tts.api.libs' to be distributed and are
              already explicitly excluding 'vnpy_tts.api.libs' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      D:\miniconda3\Lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'vnpy_tts.api.vntts' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'vnpy_tts.api.vntts' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'vnpy_tts.api.vntts' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'vnpy_tts.api.vntts' to be distributed and are
              already explicitly excluding 'vnpy_tts.api.vntts' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttsmd
      copying vnpy_tts\api\vntts\vnttsmd\vnttsmd.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttsmd
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttstd
      copying vnpy_tts\api\vntts\vnttstd\vnttstd.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttstd
      copying vnpy_tts\api\libthostmduserapi_se.so -> build\lib.win-amd64-cpython-311\vnpy_tts\api
      copying vnpy_tts\api\libthosttraderapi_se.so -> build\lib.win-amd64-cpython-311\vnpy_tts\api
      copying vnpy_tts\api\thostmduserapi_se.dll -> build\lib.win-amd64-cpython-311\vnpy_tts\api
      copying vnpy_tts\api\thosttraderapi_se.dll -> build\lib.win-amd64-cpython-311\vnpy_tts\api
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_header_define.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_header_function.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_header_on.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_header_process.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_source_function.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_source_module.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_source_on.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_source_process.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_source_switch.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_md_source_task.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_header_define.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_header_function.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_header_on.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_header_process.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_source_function.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_source_module.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_source_on.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_source_process.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_source_switch.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      copying vnpy_tts\api\generator\tts_td_source_task.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\generator
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api\include
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\attr.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\buffer_info.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\cast.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\chrono.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\common.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\complex.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\eigen.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\embed.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\eval.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\functional.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\iostream.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\numpy.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\operators.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\options.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\pybind11.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\pytypes.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\stl.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      copying vnpy_tts\api\include\pybind11\stl_bind.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11\detail
      copying vnpy_tts\api\include\pybind11\detail\class.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11\detail
      copying vnpy_tts\api\include\pybind11\detail\common.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11\detail
      copying vnpy_tts\api\include\pybind11\detail\descr.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11\detail
      copying vnpy_tts\api\include\pybind11\detail\init.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11\detail
      copying vnpy_tts\api\include\pybind11\detail\internals.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11\detail
      copying vnpy_tts\api\include\pybind11\detail\typeid.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\pybind11\detail
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api\include\tts
      copying vnpy_tts\api\include\tts\ThostFtdcMdApi.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\tts
      copying vnpy_tts\api\include\tts\ThostFtdcTraderApi.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\tts
      copying vnpy_tts\api\include\tts\ThostFtdcUserApiDataType.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\tts
      copying vnpy_tts\api\include\tts\ThostFtdcUserApiStruct.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\include\tts
      creating build\lib.win-amd64-cpython-311\vnpy_tts\api\libs
      copying vnpy_tts\api\libs\thostmduserapi_se.lib -> build\lib.win-amd64-cpython-311\vnpy_tts\api\libs
      copying vnpy_tts\api\libs\thosttraderapi_se.lib -> build\lib.win-amd64-cpython-311\vnpy_tts\api\libs
      copying vnpy_tts\api\vntts\vntts.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts
      copying vnpy_tts\api\vntts\vnttsmd\dllmain.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttsmd
      copying vnpy_tts\api\vntts\vnttsmd\framework.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttsmd
      copying vnpy_tts\api\vntts\vnttsmd\pch.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttsmd
      copying vnpy_tts\api\vntts\vnttsmd\pch.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttsmd
      copying vnpy_tts\api\vntts\vnttsmd\vnttsmd.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttsmd
      copying vnpy_tts\api\vntts\vnttstd\dllmain.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttstd
      copying vnpy_tts\api\vntts\vnttstd\framework.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttstd
      copying vnpy_tts\api\vntts\vnttstd\pch.cpp -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttstd
      copying vnpy_tts\api\vntts\vnttstd\pch.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttstd
      copying vnpy_tts\api\vntts\vnttstd\vnttstd.h -> build\lib.win-amd64-cpython-311\vnpy_tts\api\vntts\vnttstd
      running build_ext
      building 'vnpy_tts.api.vnttstd' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\vnpy_tts
      creating build\temp.win-amd64-cpython-311\Release\vnpy_tts\api
      creating build\temp.win-amd64-cpython-311\Release\vnpy_tts\api\vntts
      creating build\temp.win-amd64-cpython-311\Release\vnpy_tts\api\vntts\vnttstd
      "d:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ivnpy_tts/api/include -Ivnpy_tts/api/vntts -ID:\miniconda3\include -ID:\miniconda3\Include "-Id:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include" "-Id:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-Id:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpvnpy_tts/api/vntts/vnttstd/vnttstd.cpp /Fobuild\temp.win-amd64-cpython-311\Release\vnpy_tts/api/vntts/vnttstd/vnttstd.obj -O2 -MT
      cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
      vnttstd.cpp
      C:\Users\Administrator\AppData\Local\Temp\pip-install-faof6hlw\vnpy-tts_fc1210d6004b4750a21911eaa6d655fb\vnpy_tts\api\include\pybind11\cast.h(441): error C2027: 使用了未定义类型“_frame”
      D:\miniconda3\include\pytypedefs.h(22): note: 参见“_frame”的声明
      C:\Users\Administrator\AppData\Local\Temp\pip-install-faof6hlw\vnpy-tts_fc1210d6004b4750a21911eaa6d655fb\vnpy_tts\api\include\pybind11\cast.h(443): error C2027: 使用了未定义类型“_frame”
      D:\miniconda3\include\pytypedefs.h(22): note: 参见“_frame”的声明
      C:\Users\Administrator\AppData\Local\Temp\pip-install-faof6hlw\vnpy-tts_fc1210d6004b4750a21911eaa6d655fb\vnpy_tts\api\include\pybind11\cast.h(444): error C2027: 使用了未定义类型“_frame”
      D:\miniconda3\include\pytypedefs.h(22): note: 参见“_frame”的声明
      vnpy_tts/api/include\pybind11/pybind11.h(1890): error C2039: "frame": 不是 "_ts" 的成员
      D:\miniconda3\include\cpython/pystate.h(82): note: 参见“_ts”的声明
      vnpy_tts/api/include\pybind11/pybind11.h(1891): error C2027: 使用了未定义类型“_frame”
      D:\miniconda3\include\pytypedefs.h(22): note: 参见“_frame”的声明
      vnpy_tts/api/include\pybind11/pybind11.h(1892): error C2027: 使用了未定义类型“_frame”
      D:\miniconda3\include\pytypedefs.h(22): note: 参见“_frame”的声明
      vnpy_tts/api/include\pybind11/pybind11.h(1895): error C2027: 使用了未定义类型“_frame”
      D:\miniconda3\include\pytypedefs.h(22): note: 参见“_frame”的声明
      vnpy_tts/api/include\pybind11/pybind11.h(1894): error C2660: “PyDict_GetItem”: 函数不接受 1 个参数
      D:\miniconda3\include\dictobject.h(22): note: 参见“PyDict_GetItem”的声明
      vnpy_tts/api/include\pybind11/pybind11.h(1894): note: 尝试匹配参数列表“()”时
      vnpy_tts/api/vntts/vnttstd/vnttstd.cpp(11838): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
      error: command 'd:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vnpy_tts
  Running setup.py clean for vnpy_tts
Failed to build vnpy_tts
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (vnpy_tts)

**Comment by Lsgo** [comment]
我看论坛应该有人和我碰到一样的问题 应该是python3.11版本不支持,大佬门看一下能否修复,版本升级后续也是要升级的
https://www.vnpy.com/forum/topic/32278-pip-install-vnpy-ctpwen-ti

**Comment by vnpy** [comment]
VeighNa官方提供的二进制编译安装包只有Python 3.10版本，其他版本Python安装的时候请先确保已经安装配置好了C++编译器，比如Windows上请安装Visual Studio 2022以上即可
