### ISSUE TITLE
ubuntu vnpy_tts 无法使用

### ISSUE THREAD

**Issue by ZedRover** [vnpy/vnpy_tts#8]
安装方法：
1. pip install vnpy_tts
2. git clone 后pip install .
3. git clone 后 把 openctp 的 .so文件复制进 vnpy_tts/vnpy_tts/api 里后 pip install .
三种方法都会报错
CThostFtdcUserApiImplBase::OnSessionDisconnected[0x7fba7c000b68][-59965289][ 4097]
看到 ctp 开放平台的作者在知乎[https://zhuanlan.zhihu.com/p/453332727 ](https://zhuanlan.zhihu.com/p/453332727)上说“vn.py用户也常有连接TTS通道时碰到4097的错误，这是由于同时勾选了CTP通道、TTS通道，这两个通道动态库名字相同，会产生冲突，所以不要同时勾选这两个通道。”

**Comment by noranhe** [comment]
可参考https://github.com/vnpy/vnpy_tts/pull/9
